name: Unity WebGL Build & Netlify Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # 手動実行用
  workflow_dispatch:

env:
  UNITY_VERSION: 6000.0.43f1

jobs:
  build-and-deploy:
    name: Build WebGL and Deploy to Netlify
    runs-on: ubuntu-latest
    steps:
      # リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # ディスク容量の確保
      - name: Free disk space
        run: |
          sudo swapoff -a && sudo rm -f /swapfile
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc /usr/local/.ghcup
          sudo apt-get remove -y google-cloud-cli || sudo apt-get remove -y google-cloud-sdk
          sudo apt-get autoremove -y && sudo apt-get clean
          docker system prune -af
          df -h

      # Unity ライブラリのキャッシュ
      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-WebGL-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-WebGL-

      # Unity WebGL ビルド実行
      - name: Build Unity WebGL
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: WebGL
          buildName: WebGL
          buildsPath: build
          unityVersion: ${{ env.UNITY_VERSION }}

      # ビルドディレクトリの内容確認と権限修正
      - name: Check build directory and fix permissions
        run: |
          ls -la build || echo "build directory does not exist"
          ls -la build/WebGL || echo "build/WebGL directory does not exist"
          
          # 権限を修正
          sudo chown -R $(whoami):$(whoami) build || echo "Failed to change ownership"
          sudo chmod -R 755 build || echo "Failed to change permissions"
          
          if [ -d "build/WebGL/WebGL" ]; then
            echo "WebGL build is in build/WebGL/WebGL directory"
            ls -la build/WebGL/WebGL
            ls -la build/WebGL/WebGL/Build || echo "Build directory does not exist"
          fi

      # 一時ディレクトリに Netlify 設定ファイルを作成し、コピー
      - name: Create Netlify configuration in temp dir
        run: |
          # 一時ディレクトリに設定ファイルを作成
          mkdir -p /tmp/netlify-config
          cat > /tmp/netlify-config/netlify.toml << 'EOL'
          [build]
            publish = "WebGL"
          
          [[headers]]
            for = "/Build/*.data.br"
            [headers.values]
              Content-Encoding = "br"
              Content-Type = "application/octet-stream"

          [[headers]]
            for = "/Build/*.wasm.br"
            [headers.values]
              Content-Encoding = "br"
              Content-Type = "application/wasm"

          [[headers]]
            for = "/Build/*.js"
            [headers.values]
              Content-Type = "application/javascript"

          [[headers]]
            for = "/Build/*.js.br"
            [headers.values]
              Content-Encoding = "br"
              Content-Type = "application/javascript"
          
          [[headers]]
            for = "/*"
            [headers.values]
              Cross-Origin-Embedder-Policy = "require-corp"
              Cross-Origin-Opener-Policy = "same-origin"
          EOL
          
          # ビルドディレクトリに設定ファイルをコピー
          sudo cp /tmp/netlify-config/netlify.toml build/WebGL/
          
          # 設定ファイルの内容確認
          echo "Netlify configuration file content:"
          cat build/WebGL/netlify.toml || echo "Failed to read netlify.toml"

      # WebGL ビルドをアーティファクトとして保存
      - name: Upload WebGL build
        uses: actions/upload-artifact@v4
        with:
          name: WebGL-Build
          path: build/WebGL
          if-no-files-found: warn
      
      # Netlify にデプロイ
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: './build/WebGL'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 10