name: Unity WebGL Build & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  UNITY_VERSION: 6000.0.43f1

jobs:
  build-and-deploy:
    name: Build WebGL and Deploy
    runs-on: ubuntu-latest
    steps:
      # リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # Unity ライブラリのキャッシュ
      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-WebGL-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-WebGL-

      # Unity WebGL ビルド実行
      - name: Build Unity WebGL
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: WebGL
          buildName: WebGL
          buildsPath: build
          unityVersion: ${{ env.UNITY_VERSION }}

      # deploy ブランチにビルド結果をデプロイ
      - name: Deploy to deploy branch
        if: github.ref == 'refs/heads/main' # main ブランチの場合のみ実行
        run: |
          # 一時ディレクトリにビルド結果をコピー
          mkdir -p /tmp/webgl-build
          cp -r build/WebGL/WebGL/* /tmp/webgl-build/
          
          # netlify.toml ファイルを作成
          cat > /tmp/webgl-build/netlify.toml << 'EOL'
          [[headers]]
            for = "/Build/*.data.br"
            [headers.values]
              Content-Encoding = "br"
              Content-Type = "application/octet-stream"

          [[headers]]
            for = "/Build/*.wasm.br"
            [headers.values]
              Content-Encoding = "br"
              Content-Type = "application/wasm"

          [[headers]]
            for = "/Build/*.js"
            [headers.values]
              Content-Type = "application/javascript"

          [[headers]]
            for = "/Build/*.js.br"
            [headers.values]
              Content-Encoding = "br"
              Content-Type = "application/javascript"
          
          [[headers]]
            for = "/*"
            [headers.values]
              Cross-Origin-Embedder-Policy = "require-corp"
              Cross-Origin-Opener-Policy = "same-origin"
          EOL
          
          # SPAリダイレクト（オプション）
          echo "/* /index.html 200" > /tmp/webgl-build/_redirects
          
          # Git 設定
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # deploy ブランチをクローン
          git clone --single-branch --branch deploy https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git /tmp/deploy-branch
          
          # deploy ブランチの内容をクリア
          cd /tmp/deploy-branch
          git rm -rf . || true
          
          # ビルドファイルをコピー
          cp -r /tmp/webgl-build/* .
          
          # 変更をコミット
          git add -A
          git commit -m "Deploy WebGL build - $(date)" || echo "No changes to commit"
          git push