name: Unity WebGL Build & Netlify Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # 手動実行用
  workflow_dispatch:

env:
  UNITY_VERSION: 6000.0.43f1

jobs:
  build-and-deploy:
    name: Build WebGL and Deploy to Netlify
    runs-on: ubuntu-latest
    steps:
      # リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # ディスク容量の確保
      - name: Free disk space
        run: |
          sudo swapoff -a && sudo rm -f /swapfile
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc /usr/local/.ghcup
          sudo apt-get remove -y google-cloud-cli || sudo apt-get remove -y google-cloud-sdk
          sudo apt-get autoremove -y && sudo apt-get clean
          docker system prune -af
          df -h

      # Unity ライブラリのキャッシュ
      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-WebGL-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-WebGL-

      # Unity WebGL ビルド実行
      - name: Build Unity WebGL
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: WebGL
          buildName: WebGL
          buildsPath: build
          unityVersion: ${{ env.UNITY_VERSION }}

      # ビルド結果のディレクトリを確認
      - name: Check build directory
        run: |
          ls -la build || echo "build directory does not exist"
          ls -la build/WebGL || echo "build/WebGL directory does not exist"

      # ビルド結果の権限を変更
      - name: Fix permissions
        run: |
          sudo chown -R $USER:$USER build || echo "Failed to change ownership of build directory"
          sudo chmod -R 755 build || echo "Failed to change permissions of build directory"

      # CORS 設定ファイルを追加
      - name: Create Netlify configuration
        run: |
          mkdir -p build/WebGL || echo "Failed to create WebGL directory"
          cat > build/WebGL/netlify.toml << 'EOL'
          [[headers]]
            for = "/*"
              [headers.values]
                "Cross-Origin-Embedder-Policy" = "require-corp"
                "Cross-Origin-Opener-Policy" = "same-origin"
          EOL

      # WebGL ビルドをアーティファクトとして保存
      - name: Upload WebGL build
        uses: actions/upload-artifact@v4
        with:
          name: WebGL-Build
          path: build/WebGL
          if-no-files-found: warn
      
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0.0
        with:
          publish-dir: './build/WebGL'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 10